In [4]:
import cvxopt as co
import numpy as np
#co.solvers.options['show_progress'] = False

# Problem 1

In [2]:
G = np.array([[-1.,-2.,0.],[-2.,-10.,-3.],[-1.,0.,0.],[0.,-1.,0.],[0.,0.,-1.]])
h = np.array([-3.,-10.,0.,0.,0.])
c = np.array([2.,1.,3.])

In [3]:
G

array([[ -1.,  -2.,   0.],
       [ -2., -10.,  -3.],
       [ -1.,   0.,   0.],
       [  0.,  -1.,   0.],
       [  0.,   0.,  -1.]])

In [4]:
h

array([ -3., -10.,   0.,   0.,   0.])

In [5]:
c

array([2., 1., 3.])

In [6]:
#converting to cvxopt matrix data type
G = co.matrix(G)
h = co.matrix(h)
c = co.matrix(c)

In [7]:
#using built-in solver
sol = co.solvers.lp(c, G, h)

     pcost       dcost       gap    pres   dres   k/t
 0:  1.7500e+00  2.7750e+01  2e+01  3e-01  8e+00  1e+00
 1:  2.3244e+00  7.3350e+00  3e+00  6e-02  1e+00  3e-01
 2:  1.5194e+00  3.0005e+00  1e+00  2e-02  4e-01  2e-01
 3:  1.4996e+00  1.5212e+00  2e-02  3e-04  6e-03  2e-03
 4:  1.5000e+00  1.5002e+00  2e-04  3e-06  6e-05  2e-05
 5:  1.5000e+00  1.5000e+00  2e-06  3e-08  6e-07  2e-07
 6:  1.5000e+00  1.5000e+00  2e-08  3e-10  6e-09  2e-09
Optimal solution found.


In [8]:
#printing optimal solution to minimization problem
print (sol['x'])

[-1.15e-09]
[ 1.50e+00]
[ 6.95e-11]



In [9]:
#printing optimum value
print (sol['primal objective'])

1.4999999996249473


# Problem 2

In [10]:
def l1Min(A,b):
    n = A.shape[1]
    c = co.matrix(np.concatenate((np.ones(n), np.zeros(n))))
    G = np.concatenate((
            np.concatenate((-np.identity(n), np.identity(n)), axis=1),
            np.concatenate((-np.identity(n),-np.identity(n)), axis=1),
            np.concatenate((np.zeros(A.shape), A),axis=1),
            np.concatenate((np.zeros(A.shape), -A),axis=1)), 
        axis=0)
    h = np.concatenate((np.zeros(2*n),b, -b))
    
    #converting to cvxopt matrix data type
    G = co.matrix(G)
    h = co.matrix(h)
    c = co.matrix(c)
    
    #using built-in solver
    sol = co.solvers.lp(c, G, h)
    
    #printing optimal solution to minimization problem
    soln = (np.array(sol['x'][n:]), sol['primal objective'])
    print ("\nOptimum value of x:")
    print (sol['x'][n:])
    
    #printing optimum value
    print ("\nOptimum value of objective function:")
    print (sol['primal objective'])
    
    
    return soln

In [11]:
#Test Values
A = np.array([[1.,1.,0.,0.,0.,0.],
             [0.,0.,1.,1.,0.,0.],
             [0.,0.,0.,0.,1.,1.],
             [1.,0.,1.,0.,1.,0.],
             [0.,1.,0.,1.,0.,1.]])
b = np.array([7., 2., 4., 5., 8.])

In [12]:
optimum = l1Min(A,b)

     pcost       dcost       gap    pres   dres   k/t
 0:  0.0000e+00 -0.0000e+00  1e+02  1e+00  2e+00  1e+00
 1:  1.2425e+01  1.2886e+01  2e+01  2e-01  4e-01  7e-01
 2:  1.2841e+01  1.2920e+01  2e+00  2e-02  4e-02  1e-01
 3:  1.2998e+01  1.2999e+01  2e-02  2e-04  4e-04  1e-03
 4:  1.3000e+01  1.3000e+01  2e-04  2e-06  4e-06  1e-05
 5:  1.3000e+01  1.3000e+01  2e-06  2e-08  4e-08  1e-07
Optimal solution found.

Optimum value of x:
[ 2.59e+00]
[ 4.41e+00]
[ 8.29e-01]
[ 1.17e+00]
[ 1.58e+00]
[ 2.42e+00]


Optimum value of objective function:
12.999999848361481


# Problem 3

In [13]:
c = co.matrix([4., 7., 6., 8., 8., 9.])
G = co.matrix(np.concatenate((-np.eye(6), 
                              -np.array([0.,1.,0.,1.,0.,1.])[None], 
                              np.array([0.,1.,0.,1.,0.,1.])[None]), axis=0))
h = co.matrix(np.concatenate((np.zeros(6),[-8],[8])))
A = co.matrix(np.array([[1.,1.,0.,0.,0.,0.],
                     [0.,0.,1.,1.,0.,0.],
                     [0.,0.,0.,0.,1.,1.],
                     [1.,0.,1.,0.,1.,0.]]))
b = co.matrix([7., 2., 4., 5.])


In [14]:
sol = co.solvers.lp(c, G, h, A, b)
print (sol['x'])
print (sol['primal objective'])

     pcost       dcost       gap    pres   dres   k/t
 0:  8.9500e+01  8.9500e+01  3e+01  3e-01  2e-01  1e+00
 1:  8.6253e+01  8.6372e+01  2e+00  2e-02  2e-02  2e-01
 2:  8.5980e+01  8.6000e+01  3e-01  3e-03  3e-03  3e-02
 3:  8.6000e+01  8.6000e+01  3e-03  3e-05  3e-05  3e-04
 4:  8.6000e+01  8.6000e+01  3e-05  3e-07  3e-07  3e-06
 5:  8.6000e+01  8.6000e+01  3e-07  3e-09  3e-09  3e-08
Optimal solution found.
[ 5.00e+00]
[ 2.00e+00]
[-7.03e-09]
[ 2.00e+00]
[-5.45e-09]
[ 4.00e+00]

85.99999998207521


# Problem 4

In [21]:
P = co.matrix(np.array([[1.,2./3,1./3],[2./3,4./3,2./3],[1./3,2./3,1]]))
q = co.matrix(np.array([3.,0.,1.]))

In [29]:
sol = co.solvers.qp(P,q)
print ("Optimum X value:\n")
print (sol['x'])
print ("Optimum Objective value: ",sol['primal objective'])

Optimum X value:

[-4.50e+00]
[ 3.00e+00]
[-1.50e+00]

Optimum Objective value:  -7.5


# Problem 5

In [30]:
def l2Min(A,b):
    n = A.shape[1]
    G = np.concatenate((
            np.concatenate((-np.identity(n), np.identity(n)), axis=1),
            np.concatenate((-np.identity(n),-np.identity(n)), axis=1),
            np.concatenate((np.zeros(A.shape), A),axis=1),
            np.concatenate((np.zeros(A.shape), -A),axis=1)), 
        axis=0)
    h = np.concatenate((np.zeros(2*n),b, -b))
    P = np.eye(n)
    q = np.zeros(n)
    
    G = co.matrix(G)
    h = co.matrix(h)
    P = co.matrix(P)
    q = co.matrix(q)
    
    
    
    #using built-in solver
    sol = co.solvers.qp(P, q, G, h)
    
    #printing optimal solution to minimization problem
    soln = (np.array(sol['x'][n:]), sol['primal objective'])
    print ("\nOptimum value of x:")
    print (sol['x'][n:])
    
    #printing optimum value
    print ("\nOptimum value of objective function:")
    print (sol['primal objective'])
    
    
    return soln

In [16]:
def l2Min(A,b):
    n = A.shape[1]
    P = np.eye(n)
    q = np.zeros(n)

    G = np.concatenate((
            -np.identity(n),
            A,
            -A), 
        axis=0)
    h = np.concatenate((np.zeros(n),b,-b))
    
    
    P = co.matrix(P)
    q = co.matrix(q) 
    G = co.matrix(G)
    h = co.matrix(h)
    
    #using built-in solver
    sol = co.solvers.qp(P, q, G, h)
    
    #printing optimal solution to minimization problem
    soln = (np.array(sol['x']), sol['primal objective'])
    print ("\nOptimum value of x:")
    print (sol['x'])
    
    #printing optimum value
    print ("\nOptimum value of objective function:")
    print (sol['primal objective'])
    
    
    return soln

In [17]:
A = np.array([[1., 1.]])
b = np.array([2.])

In [18]:
l2Min(A, b)

     pcost       dcost       gap    pres   dres
 0:  4.4444e-01  0.0000e+00  9e+00  1e+00  2e+00
 1:  1.0145e+00  3.1847e-01  8e-01  3e-02  5e-02
 2:  9.9985e-01  9.8717e-01  1e-02  5e-04  1e-03
 3:  1.0000e+00  9.9987e-01  1e-04  5e-06  1e-05
 4:  1.0000e+00  1.0000e+00  1e-06  5e-08  1e-07
 5:  1.0000e+00  1.0000e+00  1e-08  5e-10  1e-09
Optimal solution found.

Optimum value of x:
[ 1.00e+00]
[ 1.00e+00]


Optimum value of objective function:
0.9999999998482699


(array([[1.],
        [1.]]), 0.9999999998482699)

# Problem 6

In [180]:
forest_data = np.load("/Users/spradhan/Downloads/Data-master/CVXOPT_Intro/ForestData.npy")


In [184]:
import pandas as pd
df=pd.DataFrame(forest_data)
df.columns = ['i', 's_i','j','p_ij','t_ij','g_ij','w_ij']
df["i"] = np.array([1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7])
df["s_i"] = np.array([75,75,57,90,90,90,140,140,140,60,60,60,212,212,212,98,98,98,113,113,113])

In [185]:
df

i  s_i    j   p_ij   t_ij  g_ij  w_ij
0   1   75  1.0  503.0  310.0  0.01  40.0
1   1   75  2.0  140.0   50.0  0.04  80.0
2   1   57  3.0  203.0    0.0  0.00  95.0
3   2   90  1.0  675.0  198.0  0.03  55.0
4   2   90  2.0  100.0   46.0  0.06  60.0
5   2   90  3.0   45.0    0.0  0.00  65.0
6   3  140  1.0  630.0  210.0  0.04  45.0
7   3  140  2.0  105.0   57.0  0.07  55.0
8   3  140  3.0   40.0    0.0  0.00  60.0
9   4   60  1.0  330.0  112.0  0.01  30.0
10  4   60  2.0   40.0   30.0  0.02  35.0
11  4   60  3.0  295.0    0.0  0.00  90.0
12  5  212  1.0  105.0   40.0  0.05  60.0
13  5  212  2.0  460.0   32.0  0.08  60.0
14  5  212  3.0  120.0    0.0  0.00  70.0
15  6   98  1.0  490.0  105.0  0.02  35.0
16  6   98  2.0   55.0   25.0  0.03  50.0
17  6   98  3.0  180.0    0.0  0.00  75.0
18  7  113  1.0  705.0  213.0  0.02  40.0
19  7  113  2.0   60.0   40.0  0.04  45.0
20  7  113  3.0  400.0    0.0  0.00  95.0

In [186]:
df=df.sort_values(by=['i','j'])
df

i  s_i    j   p_ij   t_ij  g_ij  w_ij
0   1   75  1.0  503.0  310.0  0.01  40.0
1   1   75  2.0  140.0   50.0  0.04  80.0
2   1   57  3.0  203.0    0.0  0.00  95.0
3   2   90  1.0  675.0  198.0  0.03  55.0
4   2   90  2.0  100.0   46.0  0.06  60.0
5   2   90  3.0   45.0    0.0  0.00  65.0
6   3  140  1.0  630.0  210.0  0.04  45.0
7   3  140  2.0  105.0   57.0  0.07  55.0
8   3  140  3.0   40.0    0.0  0.00  60.0
9   4   60  1.0  330.0  112.0  0.01  30.0
10  4   60  2.0   40.0   30.0  0.02  35.0
11  4   60  3.0  295.0    0.0  0.00  90.0
12  5  212  1.0  105.0   40.0  0.05  60.0
13  5  212  2.0  460.0   32.0  0.08  60.0
14  5  212  3.0  120.0    0.0  0.00  70.0
15  6   98  1.0  490.0  105.0  0.02  35.0
16  6   98  2.0   55.0   25.0  0.03  50.0
17  6   98  3.0  180.0    0.0  0.00  75.0
18  7  113  1.0  705.0  213.0  0.02  40.0
19  7  113  2.0   60.0   40.0  0.04  45.0
20  7  113  3.0  400.0    0.0  0.00  95.0

In [224]:
c = -df['p_ij'].values
G = np.concatenate((
        -df['t_ij'].values[None],
        -df['g_ij'].values[None],
        -1/788.0*df['w_ij'].values[None],
        -np.eye(21)), axis=0)
h = np.concatenate((np.array([-40000.,-5.,-70.]), np.zeros(21)))
b = np.array([
            df.loc[df["i"]==1, "s_i"].sum()*1.0,
            df.loc[df["i"]==2, "s_i"].sum()*1.0,
            df.loc[df["i"]==3, "s_i"].sum()*1.0,
            df.loc[df["i"]==4, "s_i"].sum()*1.0,
            df.loc[df["i"]==5, "s_i"].sum()*1.0,
            df.loc[df["i"]==6, "s_i"].sum()*1.0,
            df.loc[df["i"]==7, "s_i"].sum()*1.0])
A = np.concatenate((
           ((df["i"]==1).values+0.0)[None],
           ((df["i"]==2).values+0.0)[None],
           ((df["i"]==3).values+0.0)[None],
           ((df["i"]==4).values+0.0)[None],
           ((df["i"]==5).values+0.0)[None],
           ((df["i"]==6).values+0.0)[None],
           ((df["i"]==7).values+0.0)[None],
          ),axis=0)              

In [225]:
c = co.matrix(c)
G = co.matrix(G)
h = co.matrix(h)
A = co.matrix(A)
b = co.matrix(b)

In [226]:
sol = co.solvers.lp(c,G,h,A,b)

     pcost       dcost       gap    pres   dres   k/t
 0: -4.0054e+05  8.2796e+06  1e+06  1e-02  7e+01  1e+00
 1: -6.1852e+05  2.2554e+06  3e+05  3e-03  2e+01  9e+03
 2: -6.5846e+05 -2.1513e+05  4e+04  5e-04  4e+00  2e+03
 3: -6.6537e+05 -5.3422e+05  1e+04  1e-04  1e+00  5e+02
 4: -6.9656e+05  5.4374e+05  1e+06  1e-03  1e+01  9e+03
 5: -7.9607e+05 -6.4544e+05  3e+05  2e-04  1e+00  1e+04
 6: -9.7097e+05 -8.5436e+05  4e+05  1e-04  8e-01  1e+04
 7: -1.0732e+06 -1.0167e+06  2e+05  5e-05  4e-01  8e+03
 8: -1.1617e+06 -1.1329e+06  1e+05  3e-05  2e-01  4e+03
 9: -1.2595e+06 -1.2524e+06  4e+04  7e-06  5e-02  1e+03
10: -1.2814e+06 -1.2799e+06  8e+03  1e-06  9e-03  3e+02
11: -1.2859e+06 -1.2859e+06  1e+02  2e-08  1e-04  4e+00
12: -1.2860e+06 -1.2860e+06  1e+00  2e-10  1e-06  4e-02
13: -1.2860e+06 -1.2860e+06  1e-02  2e-12  1e-08  4e-04
Optimal solution found.


In [230]:
print ("Optimum value of X:")
print(np.array(1000*sol['x']))

Optimum X values:
[[2.06999997e+05]
 [1.27080437e-03]
 [1.59274557e-03]
 [2.69999999e+05]
 [7.71034417e-04]
 [6.83078644e-04]
 [4.19999998e+05]
 [8.49624544e-04]
 [7.68649064e-04]
 [1.79999980e+05]
 [1.22354473e-03]
 [1.85568808e-02]
 [1.20585892e-03]
 [6.35999998e+05]
 [1.28254260e-03]
 [2.93999998e+05]
 [1.01489241e-03]
 [1.44125276e-03]
 [3.38999998e+05]
 [6.98182274e-04]
 [1.59490437e-03]]


In [231]:
print ("Optimum value of Objective function:")
print(sol['primal objective'])

Optimum value of Objective function:
-1285985.9935941312
