In [113]:
import numpy as np
from matplotlib import pyplot as plt

# Problem 1 - Method of Steepest Descest

In [70]:
def steepest_descent( x_0, f, J, tol, maxiter):
    for i in range(maxiter):
        alpha = 1
        conv=False
        while f(x_0 - alpha * J(x_0))>=f(x_0):
            alpha = alpha/2
            if (alpha < tol):
                break
        x_1 = x_0 - alpha * J(x_0)
        if np.linalg.norm(x_1-x_0)<tol:
            conv=True
            break
        x_0=x_1
    return x_0,i+1,conv

In [71]:
f = lambda x : x[0]**2+x[1]**2
J = lambda x : np.array([2*x[0],2*x[1]])
x_0 = np.array([15,15])
tol = 10**-2
maxiter = 10

In [72]:
minx,iter,conv=steepest_descent(x_0, f, J, tol, maxiter)

In [73]:
minx,iter,conv

(array([0., 0.]), 2, True)

# Problem 2 - Conjugate Gradient Method

In [74]:
def conjugate_gradient(x_0, b, Q, tol=0.0001):
    r_0 = (Q @ x_0 - b)
    d_0 = -r_0
    k = 0
    while np.linalg.norm(r_0)>tol:
        alpha = (r_0.T @ r_0)/(d_0.T @ Q @ d_0)
        x_1 = x_0 + alpha * d_0
        r_1 = r_0 + alpha * Q @ d_0
        beta = (r_1.T @ r_1)/(r_0.T @ r_0)
        d_1 = -r_1 + beta * d_0
        k+=1
        
        r_0 = r_1
        d_0 = d_1
        x_0 = x_1
    return x_0, k
        

In [75]:
x_0 = np.array([2,3])[None].T
b = np.array([1,1])[None].T
Q = np.array([[1,0],[0,1]])

In [76]:
minx, k=conjugate_gradient(x_0, b, Q, tol=0.0001)
print("min value: \n",minx)
print("iteration value: ",k)

min value: 
 [[1.]
 [1.]]
iteration value:  1


# Problem 3 - Linear Regression

In [100]:
txt = np.loadtxt("linregression.txt")
txt.shape

(16, 7)

In [111]:
y = txt[:, 0][None].T
A = txt[:, 1:]
Q = A.T @ A
b = A.T @ y
x_0 = np.array([1,3,4,5,7,6])[None].T

In [112]:
minx, k=conjugate_gradient(x_0, b, Q, tol=0.0001)
print("min value: \n",minx)
print("iteration value: ",k)

min value: 
 [[-52.99357022]
 [  0.0710732 ]
 [ -0.42346586]
 [ -0.57256867]
 [ -0.41420359]
 [ 48.41786561]]
iteration value:  15


# Problem 4 - Logistic Regression

Could not find the data file